name: CI - RPG Project

on:
  push:
    branches: [ dev ]

permissions:
  contents: write  # Nécessaire pour git push et merge

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run tests and handle result
      run: |
        set -e
        if ! pytest; then
          echo "❌ Tests failed"
          COMMIT_NAME=$(git log -1 --pretty=format:"%s" | tr ' ' '_' | tr -dc '[:alnum:]_-')
          BRANCH_NAME="failures/${COMMIT_NAME}"
          echo "Creating branch $BRANCH_NAME"

          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git checkout -b "$BRANCH_NAME"
          git push origin "$BRANCH_NAME"
          exit 1
        else
          echo "✅ Tests passed — merging dev → main"
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git fetch origin main
          git checkout main
          git merge origin/dev --allow-unrelated-histories --no-edit || exit 1
          git push origin main
        fi
